[package]
name = "yair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
claims = "0.7.1"
clap = { version = "4.3.4", features = ["derive", "wrap_help"] }
image = "0.24.6"
